spring.application.name=Sistema-archivo

# Perfil activo (por defecto: dev)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Configuracion comun a todos los perfiles
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
