# Perfil de produccion
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

server.port=${SERVER_PORT:8081}
server.address=${SERVER_ADDRESS:0.0.0.0}

